---
apiVersion: v1
kind: Pod
metadata:
  name: traccar
spec:
  containers:
  - name: traccar
    image: docker.io/traccar/traccar:6.4-alpine
    ports:
    - hostPort: 8082
    - hostPort: 5027
      containerPort: 5027
    command: ["java", "-Xms512m", "-Xmx512m", "-Djava.net.preferIPv4Stack=true"]
    args: ["-jar", "tracker-server.jar", "conf/traccar.xml"]
    env:
    - name: CONFIG_USE_ENVIRONMENT_VARIABLES
      value: "true"
    - name: SERVER_TIMEOUT
      value: "300"
    - name: LOGGER_CONSOLE
      value: "true"
    - name: DATABASE_DRIVER
      value: "com.mysql.cj.jdbc.Driver"
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: mysql
          key: user
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql
          key: password
    - name: DATABASE_URL
      value: jdbc:mysql://traccar-mysql/traccar
  - name: stunnel
    image: localhost/stunnel:latest
    ports:
    - hostPort: 5200
    env:
    - name: CONNECT
      value: traccar-traccar:5027
  - name: mysql
    image: docker.io/library/mysql:9.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql
          key: rootPassword
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: mysql
          key: user
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql
          key: password
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: mysql
          key: database
    volumeMounts:
    - name: mysql-data
      mountPath: /var/lib/mysql
  - name: ddclient
    image: docker.io/linuxserver/ddclient:3.11.2
    env:
    - name: PROTOCOL
      valueFrom:
        secretKeyRef:
          name: ddclient
          key: protocol
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: ddclient
          key: password
    - name: USER
      valueFrom:
        secretKeyRef:
          name: ddclient
          key: user
    - name: ZONE
      valueFrom:
        secretKeyRef:
          name: ddclient
          key: zone
    - name: HOST
      valueFrom:
        secretKeyRef:
          name: ddclient
          key: host
    volumeMounts:
    - name: ddclient-config
      mountPath: /config
  volumes:
  - name: mysql-data
    persistentVolumeClaim:
      claimName: mysql-data
  - name: ddclient-config
    configMap:
      name: ddclient-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ddclient-config
data:
  ddclient.conf: |
    password_env=PASSWORD, \
    protocol_env=PROTOCOL, \
    login_env=USER,        \
    ttl=30,                \
    usev4=webv4,           \
    webv4=api.ipify.org,   \
    zone_env=ZONE,         \
    host_env=HOST
