---
apiVersion: v1
kind: Pod
metadata:
  name: traccar
spec:
  containers:
  - name: traccar
    image: docker.io/traccar/traccar:6.4-alpine
    ports:
    - hostPort: 8082
    command: ["java", "-Xms256m", "-Xmx256m", "-Djava.net.preferIPv4Stack=true"]
    args: ["-jar", "tracker-server.jar", "conf/traccar.xml"]
    env:
    - name: CONFIG_USE_ENVIRONMENT_VARIABLES
      value: "true"
    - name: SERVER_TIMEOUT
      value: "300"
    - name: LOGGER_CONSOLE
      value: "true"
    - name: DATABASE_DRIVER
      value: "com.mysql.cj.jdbc.Driver"
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: mysql
          key: user
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql
          key: password
    - name: DATABASE_URL
      value: jdbc:mysql://traccar-mysql/traccar
  - name: nginx
    image: docker.io/library/nginx:1.27-alpine
    ports:
    - hostPort: 5200
    env:
    - name: NGINX_ENVSUBST_OUTPUT_DIR
      value: /etc/nginx
    - name: NGINX_PORT
      value: "5200"
    - name: NGINX_UPSTREAM_SERVER
      value: traccar:5027
    - name: NGINX_CERTIFICATE
      value: /certificates/ca-certificate.pem
    - name: NGINX_CERTIFICATE_KEY
      value: /certificates/ca-private-key.pem
    - name: NGINX_TRUSTED_CERTIFICATE
      value: /certificates/ca-certificate.pem
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/templates
    - name: certificates
      mountPath: /certificates
  - name: mysql
    image: docker.io/library/mysql:9.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql
          key: rootPassword
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: mysql
          key: user
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql
          key: password
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: mysql
          key: database
    volumeMounts:
    - name: mysql-data
      mountPath: /var/lib/mysql
  - name: ddclient
    image: docker.io/linuxserver/ddclient:3.11.2
    env:
    - name: PROTOCOL
      valueFrom:
        secretKeyRef:
          name: ddclient
          key: protocol
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: ddclient
          key: password
    - name: USER
      valueFrom:
        secretKeyRef:
          name: ddclient
          key: user
    - name: ZONE
      valueFrom:
        secretKeyRef:
          name: ddclient
          key: zone
    - name: HOST
      valueFrom:
        secretKeyRef:
          name: ddclient
          key: host
    volumeMounts:
    - name: ddclient-config
      mountPath: /config
  volumes:
  - name: mysql-data
    persistentVolumeClaim:
      claimName: mysql-data
  - name: certificates
    secret:
      secretName: certificates
  - name: nginx-config
    configMap:
      name: nginx-config
  - name: ddclient-config
    configMap:
      name: ddclient-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf.template: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log notice;
    pid /var/run/nginx.pid;
    events {
      worker_connections 1024;
    }
    stream {
      upstream traccar {
        server ${NGINX_UPSTREAM_SERVER};
      }
      server {
        listen ${NGINX_PORT} ssl;
        proxy_pass traccar;
        ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_certificate ${NGINX_CERTIFICATE};
        ssl_certificate_key ${NGINX_CERTIFICATE_KEY};
        ssl_trusted_certificate ${NGINX_TRUSTED_CERTIFICATE};
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ddclient-config
data:
  ddclient.conf: |
    password_env=PASSWORD, \
    protocol_env=PROTOCOL, \
    login_env=USER,        \
    ttl=30,                \
    usev4=webv4,           \
    webv4=api.ipify.org,   \
    zone_env=ZONE,         \
    host_env=HOST
